---
title: "Analysis Template"
author: "Dr. Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

This is a test of some meta analysis packages and a template for the workflow.

### Summary of Results
* 

```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

install.packages(c("metafor", "meta", "dmetar",
                   "robumeta", "clubSandwich",
                   "weightr"))

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(metafor)
library(meta)
library(dmetar)
library(robumeta)
library(clubSandwich)
library(weightr)

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
# d <- read.csv("data/2019 GCA BLH.csv")



```


```{r Data_Wrangling, echo = F, comment = ""}

# yi = effect sizes (log odds ratios here), vi = sampling variances
dat <- data.frame(
  study = paste0("Study_", 1:8),
  yi = c(0.2, 0.5, 0.1, 0.8, 0.4, -0.1, 0.6, 0.3),
  vi = c(0.05, 0.07, 0.08, 0.04, 0.06, 0.09, 0.05, 0.07)
)

```


```{r model, echo = F}

# --- 1. Random-effects meta-analysis (REML + Hartung–Knapp) ---
res <- rma(yi, vi, data = dat, method = "REML", test = "knha")
summary(res)

```


```{r Graph_name, echo = F}



```


```{r Graph_name, echo = F}



```


```{r Graph_name, echo = F}



```


## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


