---
title: "Meta Analysis Workflow"
author: "Dr. Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

This is a test of some meta analysis packages and a template for the workflow.

### Summary of Results
* 

```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

install.packages(c("metafor", "meta", "dmetar",
                   "robumeta", "clubSandwich",
                   "weightr"))

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(metafor)
library(meta)
library(dmetar)
library(robumeta)
library(clubSandwich)
library(weightr)

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
d <- read.csv("data/Complied.CleanedTM.Meta.csv")



```


```{r Data_Wrangling, echo = F, comment = ""}

my_string <- "apple,banana,orange"
first_part <- str_split_fixed(my_string, ",", n = 2)[, 1]
print(first_part)

# yi = effect sizes (log odds ratios here), vi = sampling variances
d %>% 
  select(1,3,4,5,6,7,9) %>% 
  mutate(author = str_split_1(Authors, "_", n = 2)) %>% str(),
         pub_date = dmy(Publication.Year),
         pub_year = year(pub_date)) %>% str()

```


```{r model, echo = F}

# random-effects meta-analysis (REML + Hartung–Knapp)
res <- rma(yi, vi, data = dat,
           method = "REML",
           test = "knha")

summary(res)

```


```{r Graph_name, echo = F}

forest(res, slab = dat$study, xlab = "Effect Size (log OR)")
addpoly(res, row = -1) # pooled effect
?forest


# Prediction interval
predict(res, digits=2)

# --- 3. Heterogeneity statistics ---
res$I2      # proportion of variance due to heterogeneity
res$tau2    # between-study variance
res$QE      # Cochran’s Q test

# --- 4. Bias assessment ---
funnel(res)                    # funnel plot
regtest(res, model="lm")       # Egger’s regression test
# Selection model approach
selmod <- weightfunct(dat$yi, dat$vi, steps = c(0.025, 1))
summary(selmod)

# --- 5. Influence diagnostics ---
inf <- influence(res)
plot(inf)   # influence, leave-one-out

# --- 6. Meta-regression example (using study-level moderator) ---
dat$moderator <- c(0,1,0,1,0,1,0,1)  # toy moderator
res_meta_reg <- rma(yi, vi, mods = ~ moderator, data = dat, method = "REML")
summary(res_meta_reg)

# --- 7. Robust variance estimation (if dependent effect sizes) ---
# Example: cluster by study (if multiple effects per study)
rob_res <- robu(yi ~ 1, data = dat, studynum = study, var.eff.size = vi)
summary(rob_res)

# Sandwich variance estimator
coef_test(rob_res, vcov = "CR2")

# --- 8. Visualization (alternative with ggplot2) ---
# Orchard plot (from dmetar / metafor outputs)
orchard_plot(res)   # requires dmetar
```


```{r Graph_name, echo = F}



```


```{r Graph_name, echo = F}



```


## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


