---
title: "Taydin's Survival Analysis"
author: "Dr. Riley M. Anderson & Taydin R. Macon"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

What is this analysis about?

### Summary of Results
* 

```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(tidyverse) # Needed for data wrangling
library(cowplot) # Needed for publication-quality ggplots
library(survival)
library(ranger)
library(ggfortify)


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
dat1 <- read.csv("data/survival.csv")



```


```{r Data_Wrangling, echo = F, comment = ""}
dat1 <- dat1 %>% 
  mutate(across(c(
    tag_serial_number,
    hive_identity_id:report_notes,
    operation_id:crop_type
  ), factor),
  report_date = str_sub(report_submitted_at,
                        start = 1, end = 10),
  report_date = ymd(report_date)) %>% 
  mutate(tag_time = factor(paste(
    tag_serial_number, hive_age, sep = "_"
  )))


dat1 %>% 
  filter(hive_age == 0) %>% 
  select(tag_serial_number, report_date) %>% 
  mutate(start_month = month(report_date)) %>% 
  distinct() %>% 
  reframe(range(start_month))


dat1 %>% 
  select(tag_serial_number,
         state_province_long) %>% 
  group_by(tag_serial_number, state_province_long) %>% 
  tally()



surv_time <- dat1 %>% 
  select(tag_serial_number, hive_age) %>% 
  group_by(tag_serial_number) %>% 
  summarise(s_time = max(hive_age)) %>% 
  mutate(tag_time = factor(paste(tag_serial_number, s_time,
                          sep = "_"))) %>% 
  semi_join(x = dat1, y = ., by = "tag_time")
```


```{r Graph_name, echo = F}

surv_time %>% 
  ggplot(aes(x = hive_age, fill = state_province_long)) +
  geom_histogram(alpha = 0.5)

```


```{r km_curve, echo = F}

km_fit <- survfit(Surv(hive_age) ~ state_province_long,
                  data = surv_time)

summary(km_fit, times = c(1, 10, 20, 30 * (1:11)),
        max(surv_time$s_time))

autoplot(km_fit)
```


```{r cox_model, echo = F}

cox_fit <- coxph(Surv(hive_age) ~ state_province_long,
                 data = surv_time)

summary(cox_fit)

cox_fit_surv <- survfit(cox_fit)

autoplot(cox_fit_surv)
```

```{r additive_model, echo = F}

aa_fit <- aareg(Surv(hive_age) ~ state_province_long,
                data = surv_time)

autoplot(aa_fit) +
  theme_cowplot() +
  theme(strip.background = element_blank(),
        strip.text = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank())

```

## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


